In [1]:
import numpy as np
import pandas as pd

# 가위바위보

In [2]:
list_1=['가위','바위','보']
a = input('가위 바위 보중 하나를 내시오.')
b = np.random.choice(list_1)
print(a,b)
if (a == '가위' and b == '가위') or (a == '바위' and b == '바위') or (a == '보' and b == '보'):
  print('Draw')
elif (a == '가위' and b == '보') or (a == '바위' and b == '가위') or (a == '보' and b == '바위'):
  print('Win')
else:
  if a not in list_1:
    print('잘못된 값을 입력하셨습니다.')
  else:
    print('Lose')

가위 바위 보중 하나를 내시오.가위
가위 보
Win


## 문제 1)

고객의 개인정보보호를 위하여 이름을 비 식별화를 하려고 한다. 고객의 이름을 비 식별화 하여서 출력해보세요.

예시) 홍길동 -> 홍*동

In [3]:
names = ['홍길동', '홍계월', '김철수', '이영희', '박첨지']

In [4]:
for i in range(len(names)):
  names[i] = names[i].replace(names[i][1],'*')

print(names)

['홍*동', '홍*월', '김*수', '이*희', '박*지']


## 문제 2)  

‘students.txt’ 파일을 읽어서 딕셔너리로 학생들의 정보를 저장하라. 해당 파일은 이름, 국어점수, 영어점수, 수학점수 순으로 되어있으며, 각 컬럼의 구분자는 tab(\t)
으로 이루어져있다. 이름을 key로 하고, 국어점수, 영어점수, 수학점수를 순서대로 담은 리스트를 value로 하는 딕셔너리로 저장하라. (encoding을 주의하시오.)

1. read 이용

In [5]:
students = {}
with open('C:/Users/lg/Desktop/SD_academy-main/SD_academy-main/파이썬/students.txt', 'r', encoding = 'UTF-8') as f:
    data = f.read()
    lines = data.split('\n')
    for stu in lines : 
        s = stu.split('\t')
        students[s[0]] = s[1:] 
    print(students)


{'홍길동': ['50', '70', '65'], '홍계월': ['80', '90', '100'], '뽀로로': ['83', '92', '86'], '펭수': ['95', '100', '97'], '뚝딱이': ['77', '72', '87']}


### 2. readlines 이용

In [6]:
students2 = {}
with open('C:/Users/lg/Desktop/SD_academy-main/SD_academy-main/파이썬/students.txt','r',encoding = 'utf-8') as f:
  data2 = f.readlines()
  for i in data2:
    z = i.strip('\n')
    s = z.split('\t')
    students2[s[0]] = s[1:]
print(students2)

{'홍길동': ['50', '70', '65'], '홍계월': ['80', '90', '100'], '뽀로로': ['83', '92', '86'], '펭수': ['95', '100', '97'], '뚝딱이': ['77', '72', '87']}


문제 3)

저장한 딕셔너리를 토대로 학생들의 평균을 구하라. 전체 학생의 국어, 영어, 수학 점수의 평균을 구해서 각각 kor, eng, math라는 변수에 저장하고, 출력하라.


In [7]:
students

{'홍길동': ['50', '70', '65'],
 '홍계월': ['80', '90', '100'],
 '뽀로로': ['83', '92', '86'],
 '펭수': ['95', '100', '97'],
 '뚝딱이': ['77', '72', '87']}

In [8]:
for key, value in students.items():
  print(value)

['50', '70', '65']
['80', '90', '100']
['83', '92', '86']
['95', '100', '97']
['77', '72', '87']


In [9]:
kor = 0
eng = 0
math = 0
for key, value in students.items():
    kor += int(value[0])
    eng += int(value[1])
    math += int(value[2])    
kor = kor/5
eng = eng/5
math = math/5

In [10]:
print(kor,eng,math)

77.0 84.8 87.0


## 문제 4)

학생들 개개인의 평균을 구하는 함수를 작성하라. 이름을 넣으면 국어, 영어, 수학 3과목의 평균을 계산하여 반환하는 함수를 작성하라
.

In [11]:
def mean(이름):
  sum = 0
  for key, value in students.items():
    if 이름 == key:
      for i in range(len(students[이름])):
        sum += int(students[이름][i])
    sum=sum/3
  print(sum)
mean('뚝딱이')

78.66666666666667


### 문제 5)

복리이자율7%로 1000만원 저금시 2000만원이 되기까지 몇년이 걸리는가?

In [12]:
month = 0
mul = 1000
while 2000 > mul:
   mul = mul * 1.07
   month += 1
print(month)

11


## 문제 6)

다음 문장에서 모음('aeiou')을 제거하시오

문장 : "Life is too short, you need python!" (Hint : List comprehension or for 문을 사용하세요.)

In [13]:
sentence = 'Life is too short, you need python!'

In [14]:
muemum = 'aeiou'
result = [char for char in sentence if char not in muemum]
result=','.join(result)
result.replace(',','')

'Lf s t shrt y nd pythn!'

In [15]:
sentence = 'Life is too short, you need python!'
sentence
# list comprehensive
mueum ='aeiou'
result = [char for char in sentence if char not in mueum]
result = ','.join(result)
result=result.replace(',','')
result

sentence = 'Life is too short, you need python!'

for i in sentence:
  if i in ['a','i','e','o','u']:
    sentence = sentence.replace(i,'')
  sentence
sentence

'Lf s t shrt, y nd pythn!'

## 문제 7)

리스트 중에서 홀수에만 2를 곱하여 저장하는 코드 작성.

In [16]:
def 홀수(리스트):
  for i in range(len(리스트)):
    if 리스트[i]%2 != 0:
      리스트[i] = 리스트[i]*2
  return 리스트
홀수([0,1,2,3,4,5,6,7,8,9])

[0, 2, 2, 6, 4, 10, 6, 14, 8, 18]

In [17]:
홀수(np.arange(24))

array([ 0,  2,  2,  6,  4, 10,  6, 14,  8, 18, 10, 22, 12, 26, 14, 30, 16,
       34, 18, 38, 20, 42, 22, 46])

## 문제 8)

LIst Comprehension을 이용해서 list1이 1부터 100사이의 8의 배수를 가지도록 만들어 보세요



In [18]:
mul=[i for i in range(1,101) if i%8 == 0]
mul

[8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96]

## 문제 9)

Shape를 부모 클래스로 Square 자식 클래스를 정의하는 코드를 작성하십시오.

Square 클래스는 length 필드를 가지며, 0을 반환하는 Shape 클래스의 area 메서드를

length * length 값을 반환하는 메서드로 오버라이딩합니다."

## 문제 10)

Person를 부모 클래스로 Male, Female 자식 클래스를 정의하는 코드를 작성하십시오.

"Unknown"을 반환하는 Person 클래스의 getGender 메서드를 Male 클래스와 Female 클래스는

"Male", "Female" 값을 반환하는 메서드로 오버라이딩합니다.


## 문제 11)

행렬의 덧셈은 행과 열의 크기가 같은 두 행렬의 같은 행, 같은 열의 값을 서로 더한 결과가 됩니다. 2개의 행렬 arr1과 arr2를 입력받아, 행렬 덧셈의 결과를 반환하는 함수, solution을 완성해주세요.

제한 조건 행렬 arr1, arr2의 행과 열의 길이는 500을 넘지 않습니다.

문제풀이1) for 문 작성 문제풀이2) zip 함수 이용 문제풀이3) list comprehension을 이용



In [19]:
arr1 = np.arange(36).reshape(6,-1)
arr2 = np.arange(36).reshape(6,-1)
sum = 0
arr3 = np.zeros(36).reshape(6,-1)
def solution(arr3):
  for i in range(len(arr1)):
    for j in range(len(arr1)):
        arr3[i][j] = arr1[i][j]+arr2[i][j]
  print(arr3)
solution(arr3)

[[ 0.  2.  4.  6.  8. 10.]
 [12. 14. 16. 18. 20. 22.]
 [24. 26. 28. 30. 32. 34.]
 [36. 38. 40. 42. 44. 46.]
 [48. 50. 52. 54. 56. 58.]
 [60. 62. 64. 66. 68. 70.]]


In [20]:
ziparr=zip(arr1,arr2)
arr3 = np.zeros(36).reshape(6,-1)
def solution1(ziparr):  
  for i in ziparr:
    sum = i[0] + i[1]
    print(sum)
solution1(ziparr)

[ 0  2  4  6  8 10]
[12 14 16 18 20 22]
[24 26 28 30 32 34]
[36 38 40 42 44 46]
[48 50 52 54 56 58]
[60 62 64 66 68 70]


In [21]:
arr3 = np.zeros(36).reshape(6,-1)

# def solution3(arr1,arr2):
#     [for i in range(len(arr1))]
a=[[arr1[i] for i in range(len(arr1))][j]+[arr2[i] for i in range(len(arr2))][j] for j in range(len(arr2))]
a

[array([ 0,  2,  4,  6,  8, 10]),
 array([12, 14, 16, 18, 20, 22]),
 array([24, 26, 28, 30, 32, 34]),
 array([36, 38, 40, 42, 44, 46]),
 array([48, 50, 52, 54, 56, 58]),
 array([60, 62, 64, 66, 68, 70])]

## 문제 12)


1부터 입력받은 숫자 n 사이에 있는 소수의 개수를 반환하는 함수, solution을 만들어 보세요.
소수는 1과 자기 자신으로만 나누어지는 수를 의미합니다.
(1은 소수가 아닙니다.)


[제한 조건]


n은 2이상 1000000이하의 자연수입니다.

n	result

10	4

5	3

입출력 예 설명

입출력 예 #1

1부터 10 사이의 소수는 [2,3,5,7] 4개가 존재하므로 4를 반환


입출력 예 #2

1부터 5 사이의 소수는 [2,3,5] 3개가 
존재하므로 3를 반환

In [22]:
def solution(x):
    sum = 0
    if x > 1000000:
        print('2 이상 1000000의 수만 입력해 주세요')
    else:
        for i in range(2,x+1):
            s = 0
            for j in range(2,x+1):
                if i%j == 0:
                    s += 1
            if s == 1:
                sum += 1
        print(sum)

In [23]:
solution(2)

1


## 문제 15) 

로또 번호 자동생성기를 작성하세요(Numpy를 모르시면 random 모듈로도 구현가능)


In [24]:
np.random.choice(range(1,46),6)

array([19,  7, 10, 44, 26, 44])

In [25]:
print('**************로또 번호 자동 생성기****************')
print('---------------------------------------------------')
x = int(input('게임 수: '))
for i in range(x):
  print(np.random.choice(range(1,46),6))

print('**************로또 번호 자동 완료 *****************')

**************로또 번호 자동 생성기****************
---------------------------------------------------
게임 수: 5
[ 5 37 12 26 38 17]
[ 5 42 31 40 20 11]
[16 12 42 13  1 33]
[11  1  6 13 33 26]
[ 2  1 12 21 10 31]
**************로또 번호 자동 완료 *****************


In [26]:
x = int(input('로또를 몇장 구매하시겠습니까? '))
print('랜덤하게 생성된 로또 번호입니다.')
for i in range(x):
  print(f'[{i+1}]: {np.random.choice(range(1,46),6)}')

로또를 몇장 구매하시겠습니까? 5
랜덤하게 생성된 로또 번호입니다.
[1]: [11  7  9 33  1 30]
[2]: [12 35 36 29 44 42]
[3]: [ 3 35 27 35 15 12]
[4]: [ 1 19 28 15 42 31]
[5]: [11 31  2 40  5 35]


###문제 16) 비트연산 문제

이 문제의 핵심은 비트 연산을 얼마나 잘 이해하고 있냐이기 때문에 비트 연산으로 풀어주세요.¶
input은 int n을 입력 받아 첫번째 row는 (n-1)의 O와 X, 두번째 row는 (n-2)의 O와 XX, 세번째 row는 (n-3)의 0와 XXX... n번째 row는 n의 X을 출력하시오.

입력 예시: 6

출력 예시:

OOOOOX

OOOOXX

OOOXXX

OOXXXX

OXXXXX

XXXXXX



In [27]:
x = int(input('숫자 n을 입력하시오:'))
for i in range(x+1):
  print('o'*(x-i) +'x'*(i+1))

숫자 n을 입력하시오:5
ooooox
ooooxx
oooxxx
ooxxxx
oxxxxx
xxxxxx


## 문제 17)

아래 조건에 따라 리스트를 회전하는 프로그램을 작성하시오.
조건 입력값은 한 행의 문자열로 주어지며, 각 값은 공백으로 구분된다.

첫 번째 값은 리스트를 회전하는 양과 방향(음수의 경우 좌측으로, 양수의 경우 우측으로 회전)이다.

첫 번째 값을 제외한 나머지 값은 리스트의 각 항목의 값이다.

회전된 리스트를 문자열로 출력한다.

구현에 이용할 자료구조에 대한 조건이나 제약은 없다.

입력되는 리스트의 항목의 개수는 유한한다.

입출력예 예 1)

입력: 1 10 20 30 40 50

출력: 50 10 20 30 40

예 2)

입력: 4 가 나 다 라 마 바 사

출력: 라 마 바 사 가 나 다

예 3)

입력: -2 A B C D E F G

출력: C D E F G A B

예 4)

입력: 0 똘기 떵이 호치 새초미

출력: 똘기 떵이 호치 새초미

In [28]:
def 회전(x):
    x = x.split()
    a = int(x[0])
    del(x[0])
    c = x.copy()
    if a <= 0:
        for i in range(len(x)):
            b = i + a
            while b <= -len(x) :
                b += len(x)
            c[b] = x[i]
    else:
        for i in range(len(x)):
            b = i + a
            while b >= len(x):
                b -= len(x)
            c[b] = x[i]
    print(','.join(c).replace(',',' '))

In [29]:
회전('3 똘기 떵이 호치 새초미')

떵이 호치 새초미 똘기


## 문제 18)

숫자 형태의 문자열을 콤마가 포함된 금액 표기식 문자열로 바꾸어주는 프로그램을 작성하시오.
※ 단, 프로그래밍 언어에서 지원하는 금액변환 라이브러리는 사용하지 말것

예)

숫자 금액 1000 -> 1,000

20000000 -> 20,000,000

3245.24 -> -3,245.24

In [30]:
x = '7000000000000000'
def 숫자변환기(x):
    a = ''
    s = []
    for i in range(len(x)):
        if x[i] == '.':
            c=x[i:]
            b=x[:i]
        else:
            c = ''
            b = x
    for j in reversed(range(len(b))):
        a =b[j]+ a
        s.append(j)
        if len(s)%3 == 0 and j!= 0:
            a =  ',' +a 
    print(a + c)
숫자변환기(x)

7,000,000,000,000,000


## 문제 19)

약수를 모두 찾는 수학 문제를 풀다가 지친 X는 컴퓨터의 도움을 받아 문제를 풀어 보기로 하였다. 하지만 계산기를 이용하자니 계산기로 하고 싶지만 찾기도 어려우며, 쉽게 찾아낼 수도 없었다.
풀이에 지친 그는 결국 약수들이 가지고 있는 특징을 찾아 결국 몇시간에 걸쳐 복잡한 수라도 약수를 찾아줄 수 있고 개수도 알려주는 프로그램을 짜게 된다.

다음은 약수를 얻기 위한 입력과 출력 예제들이다.

입력 1

24 출력 1

{ 1, 2, 3, 4, 6, 8, 12, 24} 약수의 개수는 8개 입니다. 입력 2

36 출력 2

{ 1, 2, 3, 4, 6, 9, 12, 18, 36 } 약수의 개수는 9개 입니다. 입력 3

2468013579 출력 3

{ 1, 3, 9, 61, 183, 549, 4495471, 13486413, 40459239, 274223731, 822671193, 2468013579 } 약수의 개수는 12개 입니다. 사용한 소스코드를 풀이에 넣어 입력과 출력이 나왔음을 보이고, 소스코드를 디버깅하여 123456789를 입력해 출력된 결과를 '{ a, b, ... } / 약수의 개수는 ~개 입니다' 형식으로 하시오.

In [31]:
def 약수찾기(num):
    a = []
    for i in range(num):
        if num%(i+1) == 0:
            a.append(i+1)
    a=set(a)
    print(sorted(a))
    print(f'약수의 개수는 {len(a)}개 입니다.')
num = 50
약수찾기(num)

[1, 2, 5, 10, 25, 50]
약수의 개수는 6개 입니다.


## 문제 20)

 2^15 = 32768 의 각 자리수를 더하면 3 + 2 + 7 + 6 + 8 = 26 입니다. 2^1000의 각 자리수를 모두 더하면 얼마입니까?

In [32]:
num = 2**15
def 자리수더하기(x):
    x = str(x)
    sum = 0
    for i in range(len(x)):
        sum += int(x[i])
    return sum

In [33]:
자리수더하기(2**1000)

1366

문제 21)

아래와 같은 결과를 출력하는 function을 구현하라
bool OneEditApart(string s1, string s2)

OneEditApart("cat", "dog") = false

OneEditApart("cat", "cats") = true

OneEditApart("cat", "cut") = true

OneEditApart("cat", "cast") = true

OneEditApart("cat", "at") = true

OneEditApart("cat", "acts") = false

한개의 문자를 삽입, 제거, 변환을 했을때 s1, s2가 동일한지를 판별하는 OneEditApart 함수를 작성하시오.

In [34]:
def OneEditApart(a,b):
    for i in range(len(a)):
        for j in range(len(b)):
            if a[i] == b[j]:
                print('굳')
OneEditApart("cat", "acts")
# 이건 모르겟다!!

굳
굳
굳


## 문제 21) 시침과 분침이 직각이 되는 순간?


###  문제

> 일반적인 1부터 12까지 아라비아 숫자가 적혀있는 시계가 있습니다.<Br>
> 이 시계는 오전 12:00 정각에 작동하기 시작하여 하루동안 움직이게 되어있습니다.<Br>
> 이 때 시침과 분침이 **직각**이 될 때의 시간을 hh:mm 형태로 나타내고 하루동안 직각이 된 총 횟수를 구해보세요!

### 출력(예시)
> 1. 09:00<p>
> 2. 15:00<p>
> ...<p>
> Total: n번!<p>

<p><p>
시간표현은 오전, 오후가 아닌 24시 방식으로 써주세요!

## 문제 22)

2진법이란, 어떤 자연수를 0과 1로만 나타내는 것이다. 

예를 들어 73은 64(2^6)+8(2^3)+1(2^0)이기 때문에 1001001으로 표현한다. 

어떤 숫자를 입력받았을 때 그 숫자를 2진법으로 출력하는 프로그램을 작성하시오.

In [35]:
def 이진법(x):
    a = ''
    b= x
    for i in reversed(range(x)):
        if 2**i > x  and  2**i < b:
            a = a + '0'
        if 2**i <= x:
            x = x - (2**i)
            a = a + '1'
    return a

In [36]:
이진법(73)

'1001001'

## 문제 23) 가성비 최대화

기계를 구입하려 하는데 이 기계는 추가 부품을 장착할 수 있다. 추가 부품은 종류당 하나씩만 장착 가능하고, 모든 추가 부품은 동일한 가격을 가진다.

원래 기계의 가격과 성능, 추가 부품의 가격과 각 부품의 성능이 주어졌을 때, 추가 부품을 장착하여 얻을 수 있는 최대 가성비를 정수 부분까지 구하시오(가격 및 성능은 상대적인 값으로 수치화되어 주어진다).

e.g.)

원래 기계의 가격 : 10

원래 기계의 성능 : 150

추가 부품의 가격 : 3

추가 부품의 성능 : 각각 30, 70, 15, 40, 65

추가 부품을 장착하여 얻을 수 있는 최대 가성비 : 17.81... → 17

(성능이 70과 65인 부품을 장착하면 됨)





In [37]:
a = 10
b= 150
c = 3
d= [30,70,15,40,65]
f = 0
d.sort(reverse = True)
x = []
for i in d:
  f += i
  x.append(i)
  if (f+b) / (c*len(x) + a) > ((f-i) + b)/(c*(len(x)-1) + a):
    print(i)
    print(str((f+b) / (c*len(x) + a))[:2])
    

70
16
65
17


In [38]:
a = 10
b = 150
c = 3
d = [30,70,15,40,65]
f = 0

d.sort(reverse = True)
x =[]

for i in d:
    f += i
    x.append(i)
    if (f+b)/(c*len(x) + a) > ((f-i) + b) / (c*(len(x) - 1) + a):
        print(i)
        print(str((f+b)/ (c*len(x) + a))[:2])        

70
16
65
17
